/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_Pins.h"
#include "CapSense_TunerHelper.h"
#include "I_Source_ADC.h"
#include "Gate_Drive_aliases.h"
#include "Gate_Drive.h"
#include "VRef_aliases.h"
#include "VRef.h"
#include "Offset_Gain.h"
#include "Offset_DAC_aliases.h"
#include "Offset_DAC.h"
#include "O_Buffer.h"
#include "Offset.h"
#include "Gate_Drive_Tune.h"
#include "Gate_Drive_Tune_DAC_aliases.h"
#include "Gate_Drive_Tune_DAC.h"
#include "GDT_Buffer.h"
#include "Source_Sense_aliases.h"
#include "Source_Sense.h"
#include "I_Sense_High_aliases.h"
#include "I_Sense_High.h"
#include "Source_ADC.h"
#include "USBUART.h"
#include "USBUART_audio.h"
#include "USBUART_cdc.h"
#include "USBUART_hid.h"
#include "USBUART_midi.h"
#include "USBUART_pvt.h"
#include "USBUART_cydmac.h"
#include "USBUART_msc.h"
#include "Output_On_LED_aliases.h"
#include "Output_On_LED.h"
#include "I_Sense_Low_aliases.h"
#include "I_Sense_Low.h"
#include "LCD.h"
#include "ConversionClock.h"
#include "SourceDMA_dma.h"
#include "BufferDMA_dma.h"
#include "PIDIsr.h"
#include "CurrentDMA_dma.h"
#include "Bootloadable.h"
#include "UART.h"
#include "CapSense_CompCH0.h"
#include "CapSense_IdacCH0.h"
#include "CapSense_AMuxCH0.h"
#include "CapSense_IntClock.h"
#include "I_Source_ADC_Ext_CP_Clk.h"
#include "I_Source_ADC_theACLK.h"
#include "Source_ADC_theACLK.h"
#include "USBUART_Dm_aliases.h"
#include "USBUART_Dm.h"
#include "USBUART_Dp_aliases.h"
#include "USBUART_Dp.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

